<a href="https://colab.research.google.com/github/lisperey/Atividades-Phyton/blob/main/filaPrioridade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
class FilaPrioridade:
    def __init__(self, capacidade):
        self.capacidade = capacidade
        self.numero_elemento = 0 
        self.valores = np.empty(self.capacidade, dtype =int)

    def __fila_vazia(self):
      return self.numero_elemento==0

    def __fila_cheia(self):
      return self.numero_elemento==self.capacidade
    
    def enfileirar(self, valor):
        if self.__fila_cheia():
            return print('A fila está cheia!!!')
            
        if self.numero_elemento==0:
            self.valores[self.numero_elemento]=valor
            self.numero_elemento+=1
        else:
            x = self.numero_elemento-1
            while x>=0:
                if valor>self.valores[x]:
                    self.valores[x+1]=self.valores[x]
                else:
                    break
                x-=1
            self.valores[x+1]=valor
            self.numero_elemento+=1

    def desenfileirar(self):
        if self.__fila_vazia():
            return print('A fila está vazia!!!')
             
        valor = self.valores[self.numero_elemento-1]
        self.numero_elemento-=1
        return valor

    def primeiro(self):
        if self.__fila_vazia():
            return -1
        return self.valores[self.numero_elemento-1]


    

In [ ]:
fila = FilaPrioridade(5)

In [ ]:
fila.primeiro()

-1

In [ ]:
fila.valores

array([44319824,        0,        0,        0,        0])

In [ ]:
fila.enfileirar(30)
fila.primeiro()
fila.valores

array([                 30, 4598175219545276416, 4602678819172646912,
       4604930618986332160, 4607182418800017408])

In [ ]:
fila.enfileirar(50)
fila.primeiro()
fila.valores

array([                 50,                  30, 4602678819172646912,
       4604930618986332160, 4607182418800017408])

In [ ]:
fila.enfileirar(10)

fila.valores


array([                 50,                  30,                  10,
       4604930618986332160, 4607182418800017408])

In [ ]:
fila.primeiro()

10

In [ ]:
fila.desenfileirar()
fila.valores

array([                 50,                  30,                  10,
       4604930618986332160, 4607182418800017408])